---
# tasks file for btrfssubvol

- name: Check public role variable syntax
  ansible.builtin.assert:
    that:
      # btrfssubvol_device_uuid is a string
      - btrfssubvol_device_uuid is defined
      - btrfssubvol_device_uuid is not none
      - btrfssubvol_device_uuid is string
      - btrfssubvol_device_uuid | length > 0

      # btrfssubvol_mount_parent is a string
      - btrfssubvol_mount_parent is defined
      - btrfssubvol_mount_parent is not none
      - btrfssubvol_mount_parent is string
      - btrfssubvol_mount_parent | length > 0
      - btrfssubvol_mount_parent[0] == "/"

      # btrfssubvol_mount_options is a list
      - btrfssubvol_mount_options is defined
      - btrfssubvol_mount_options is not none
      - btrfssubvol_mount_options is not string
      - btrfssubvol_mount_options is not mapping
      - btrfssubvol_mount_options is iterable

      # btrfssubvol_subvolumes is a list
      - btrfssubvol_subvolumes is defined
      - btrfssubvol_subvolumes is not none
      - btrfssubvol_subvolumes is not string
      - btrfssubvol_subvolumes is not mapping
      - btrfssubvol_subvolumes is iterable
    fail_msg: Public role variable have bad syntax. Check your configuration.
    success_msg: Syntax correct for public role variables.
    quiet: true
  tags:
    - checks
    - checks-syntax

- name: Include checks for btrfssubvol_mount_options
  ansible.builtin.include_tasks:
    file: checks-syntax-var-mount-options.yaml
  tags:
    - checks
    - checks-syntax
  vars:
    mount_options: "{{ btrfssubvol_mount_options }}"
    label_for_check: "'btrfssubvol_mount_options'"

- name: Check btrfssubvol_subvolumes syntax
  ansible.builtin.assert:
    that:
      # subvolume.name is a string
      - subvolume.name is defined
      - subvolume.name is not none
      - subvolume.name is string
      - subvolume.name | length > 0

      # subvolume.owner is not defined or is a string
      - >
        (subvolume.owner is not defined) or
        (subvolume.owner is not none)
      - >
        (subvolume.owner is not defined) or
        (subvolume.owner is string)
      - >
        (subvolume.owner is not defined) or
        (subvolume.owner | length > 0)

      # subvolume.group is not defined or is a string
      - >
        (subvolume.group is not defined) or
        (subvolume.group is not none)
      - >
        (subvolume.group is not defined) or
        (subvolume.group is string)
      - >
        (subvolume.group is not defined) or
        (subvolume.group | length > 0)

      # subvolume.mount_options is not defined or is a list
      - >
        (subvolume.mount_options is not defined) or
        (subvolume.mount_options is not none)
      - >
        (subvolume.mount_options is not defined) or
        (subvolume.mount_options is not string)
      - >
        (subvolume.mount_options is not defined) or
        (subvolume.mount_options is not mapping)
      - >
        (subvolume.mount_options is not defined) or
        (subvolume.mount_options is iterable)
      - >
        (subvolume.mount_options is not defined) or
        (subvolume.mount_options | length > 0)

      # subvolume.mount_point is not defined or is a string
      - >
        (subvolume.mount_point is not defined) or
        (subvolume.mount_point is not none)
      - >
        (subvolume.mount_point is not defined) or
        (subvolume.mount_point is string)
      - >
        (subvolume.mount_point is not defined) or
        (subvolume.mount_point | length > 0)
      - >
        (subvolume.mount_point is not defined) or
        (subvolume.mount_point[0] == "/")

      # subvolume.mount_state is not defined or is a string
      - >
        (subvolume.mount_state is not defined) or
        (subvolume.mount_state is not none)
      - >
        (subvolume.mount_state is not defined) or
        (subvolume.mount_state is string)
      - >
        (subvolume.mount_state is not defined) or
        (subvolume.mount_state | length > 0)
      - >
        (subvolume.mount_state is not defined) or
        (subvolume.mount_state in ["absent", "absent_from_fstab", "mounted", "present", "unmounted", "remounted", "ephemeral"])

      # subvolume.recurse is not defined or is a boolean
      - >
        (subvolume.recurse is not defined) or
        (subvolume.recurse is not none)
      - >
        (subvolume.recurse is not defined) or
        (subvolume.recurse is boolean)
    fail_msg: |
      Item syntax of 'btrfssubvol_subvolumes' is faulty. Ensure your list items
      have following syntax:

      - name (string, mandatory)

      - owner (string, optional)
      - group (string, optional)
      - mount_options (list / elements=string, optional)
      - mount_state (string, optional)
      - recurse (boolean, optional)

      Consult the documentation for further information on the values.
    success_msg: All items in 'btrfssubvol_subvolumes' have correct syntax.
    quiet: true
  loop: "{{ btrfssubvol_subvolumes }}"
  loop_control:
    loop_var: subvolume
  tags:
    - checks
    - checks-syntax

- name: Include checks for mount_options per btrfssubvol_subvolumes item
  ansible.builtin.include_tasks:
    file: checks-syntax-var-mount-options.yaml
  loop: "{{ btrfssubvol_subvolumes }}"
  loop_control:
    loop_var: subvolume
    label: "{{ subvolume.name }}"
  tags:
    - checks
    - checks-syntax
  vars:
    mount_options: "{{ subvolume.mount_options }}"
    label_for_check: "subvolume '{{ subvolume.name }}'"
  when:
    - subvolume.mount_options is defined

# End of file
