---
# tasks file for btrfssubvol

# ---------- Checks ----------

- name: Include checks for role variable syntax
  ansible.builtin.include_tasks:
    file: checks-syntax.yaml
  tags:
    - checks
    - checks-syntax

- name: Include checks for host configuration
  ansible.builtin.include_tasks:
    file: checks-host-config.yaml
  tags:
    - checks
    - checks-host-config

# ---------- Configure ----------

- name: Mount btrfs root volume
  ansible.posix.mount:
    src: "/dev/disk/by-uuid/{{ btrfssubvol_device_uuid }}"
    path: "{{ btrfssubvol_rootvol_mount_point }}"
    opts: defaults,noatime,discard,compress=zstd,subvolid=5
    state: ephemeral
    fstype: btrfs
  become: true
  check_mode: false

- name: Create subvolumes
  ansible.builtin.include_tasks:
    file: tasks/subvolumes.yaml
  loop: "{{ btrfssubvol_subvolumes }}"
  loop_control:
    loop_var: subvolume

- name: Unmount btrfs root volume
  ansible.posix.mount:
    path: "{{ btrfssubvol_rootvol_mount_point }}"
    state: unmounted
  become: true
  check_mode: false

# End of file
