---
# tasks file for btrfssubvol

# ---------- Checks ----------

- name: Check public role variable syntax
  ansible.builtin.assert:
    that:
      # btrfssubvol_device_uuid is a string
      - btrfssubvol_device_uuid is defined
      - btrfssubvol_device_uuid is not none
      - btrfssubvol_device_uuid is string
      - btrfssubvol_device_uuid | length > 0

      # btrfssubvol_rootvol_mount_point is a string
      - btrfssubvol_rootvol_mount_point is defined
      - btrfssubvol_rootvol_mount_point is not none
      - btrfssubvol_rootvol_mount_point is string
      - btrfssubvol_rootvol_mount_point | length > 0

      # btrfssubvol_subvolumes is a list
      - btrfssubvol_subvolumes is defined
      - btrfssubvol_subvolumes is not none
      - btrfssubvol_subvolumes is not string
      - btrfssubvol_subvolumes is not mapping
      - btrfssubvol_subvolumes is iterable
    fail_msg: Public role variable have bad syntax. Check your configuration.
    success_msg: Your configuration is correct.
    quiet: true

- name: Check btrfssubvol_subvolumes syntax
  ansible.builtin.assert:
    that:
      # subvolume.name is a string
      - subvolume.name is defined
      - subvolume.name is not none
      - subvolume.name is string
      - subvolume.name | length > 0

      # subvolume.owner is a string
      - (subvolume.owner is undefined) or (subvolume.owner is not none)
      - (subvolume.owner is undefined) or (subvolume.owner is string)
      - (subvolume.owner is undefined) or (subvolume.owner | length > 0)

      # subvolume.group is a string
      - (subvolume.group is undefined) or (subvolume.group is not none)
      - (subvolume.group is undefined) or (subvolume.group is string)
      - (subvolume.group is undefined) or (subvolume.group | length > 0)

      # subvolume.recurse is a boolean
      - (subvolume.recurse is undefined) or (subvolume.recurse is not none)
      - (subvolume.recurse is undefined) or (subvolume.recurse is boolean)
  loop: "{{ btrfssubvol_subvolumes }}"
  loop_control:
    loop_var: subvolume

# ---------- Configure ----------

- name: Mount btrfs root volume
  ansible.posix.mount:
    src: "/dev/disk/by-uuid/{{ btrfssubvol_device_uuid }}"
    path: "{{ btrfssubvol_rootvol_mount_point }}"
    opts: defaults,noatime,discard,compress=zstd,subvolid=5
    state: ephemeral
    fstype: btrfs
  become: true

- name: Create subvolumes
  ansible.builtin.include_tasks:
    file: tasks/subvolumes.yaml
  loop: "{{ btrfssubvol_subvolumes }}"
  loop_control:
    loop_var: subvolume

- name: Unmount btrfs root volume
  ansible.posix.mount:
    path: "{{ btrfssubvol_rootvol_mount_point }}"
    state: unmounted
  become: true

# End of file
