---
# tasks file for btrfssubvol

# ---------- Checks ----------

- name: "Include checks for role variable syntax"
  ansible.builtin.include_tasks:
    file: checks-syntax.yaml
  tags:
    - checks
    - checks-syntax

- name: "Include checks for host configuration"
  ansible.builtin.include_tasks:
    file: checks-host-config.yaml
  tags:
    - checks
    - checks-host-config

# ---------- Configure ----------

- name: "Create subvolumes"
  ansible.builtin.include_tasks:
    file: tasks/subvolumes.yaml
    apply:
      tags:
        - configure
  loop: "{{ btrfssubvol_subvolumes }}"
  loop_control:
    loop_var: subvolume
  tags:
    - configure

# End of file
