---
# tasks file for btrfssubvol

- name: "Print information start subvolume configuration"
  ansible.builtin.debug:
    msg: "========== Start configuring subvolume '{{ subvolume.name }}' =========="

# ---------- Preparations ----------

- name: Set variable subvolume_mount_option_subvol
  ansible.builtin.set_fact:
    subvolume_mount_option_subvol:
      - "{{ 'subvol=/@' ~ subvolume.name }}"

- name: Set mount options defaults if none are specified
  ansible.builtin.set_fact:
    btrfssubvol_mount_options:
      - defaults
  when:
    - btrfssubvol_mount_options | length == 0

- name: Set variable subvolume_mount_options
  ansible.builtin.set_fact:
    subvolume_mount_options: "{{
        (subvolume.mount_options | default(btrfssubvol_mount_options | default(['defaults']))
        + subvolume_mount_option_subvol) | join(',')
      }}"

# ---------- Configuration ----------

- name: Create subvolume {{ subvolume.name }}
  community.general.btrfs_subvolume:
    name: "/@{{ subvolume.name }}"
    state: present
    filesystem_uuid: "{{ btrfssubvol_device_uuid }}"
    automount: true
  become: true

- name: Manage mount and /etc/fstab state of subvolume {{ subvolume.name }}
  ansible.posix.mount:
    src: "UUID={{ btrfssubvol_device_uuid }}"
    fstype: btrfs
    path: "{{ subvolume.mount_point | default((btrfssubvol_mount_parent, subvolume.name) | path_join) }}"
    state: "{{ subvolume.mount_state | default('mounted') }}"
    opts: "{{ subvolume_mount_options }}"
    passno: 0
  become: true

- name: Set permissions for subvolume {{ subvolume.name }}
  ansible.builtin.file:
    path: "{{ subvolume.mount_point | default((btrfssubvol_mount_parent, subvolume.name) | path_join) }}"
    owner: "{{ subvolume.owner | default('root') }}"
    group: "{{ subvolume.group | default('root') }}"
    recurse: "{{ subvolume.recurse | default(false) }}"
  become: true
  diff: true
  ignore_errors: "{{ ansible_check_mode }}"
  when:
    - (subvolume.mount_state | default('mounted')) == "mounted"

# ---------- Clean-Up ----------

- name: Set internal variables to null
  ansible.builtin.set_fact:
    subvolume_mount_options: null

- name: "Print information finish subvolume configuration"
  ansible.builtin.debug:
    msg: "========== Finished configuring subvolume '{{ subvolume.name }}' =========="

# End of file
