---
# tasks file for btrfssubvol

- name: Set variable btrfssubvol_subvolume_full_path
  ansible.builtin.set_fact:
    btrfssubvol_subvolume_full_path: "{{ btrfssubvol_rootvol_mount_point }}/@{{ subvolume.name }}"

- name: Check if subvolume already exists
  ansible.builtin.stat:
    path: "{{ btrfssubvol_subvolume_full_path }}"
  become: true
  register: btrfssubvol_folder

- name: Create subvolume {{ subvolume.name }}
  ansible.builtin.command:
    cmd: btrfs subvolume create {{ btrfssubvol_subvolume_full_path }}
  become: true
  changed_when: "btrfssubvol_create.rc == 0"
  failed_when: "btrfssubvol_create.rc != 0"
  register: btrfssubvol_create
  when: not btrfssubvol_folder.stat.exists

- name: Set permissions for subvolume {{ subvolume.name }}
  ansible.builtin.file:
    path: "{{ btrfssubvol_subvolume_full_path }}"
    owner: "{{ subvolume.owner | default('root') }}"
    group: "{{ subvolume.group | default('root') }}"
    recurse: "{{ subvolume.recurse | default(false) }}"
  become: true
  diff: true

- name: Check if mountpoint already exists
  ansible.builtin.stat:
    path: "/media/{{ subvolume.name }}"
  become: true
  register: btrfssubvol_mountpoint

- name: Create mountpoint for subvolume {{ subvolume.name }}
  ansible.builtin.file:
    path: "/media/{{ subvolume.name }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true
  diff: true
  when: not btrfssubvol_mountpoint.stat.exists

- name: Mount subvol and add fstab entry
  ansible.posix.mount:
    src: "UUID={{ btrfssubvol_device_uuid }}"
    fstype: btrfs
    path: "/media/{{ subvolume.name }}"
    state: mounted
    opts: "defaults,noatime,discard,compress=zstd,subvol=/@{{ subvolume.name }}"
    passno: 0
  become: true
  diff: true

- name: Set internal variables to null
  ansible.builtin.set_fact:
    btrfssubvol_create: null
    btrfssubvol_folder: null
    btrfssubvol_mountpoint: null
    btrfssubvol_subvolume_full_path: null

# End of file
